##### 1st

In [40]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', None, 'display.max_columns', None)

In [2]:
df1 = pd.read_csv("API_NY.GDP.MKTP.CD_DS2_en_csv_v2_581470.csv", skiprows=4)
df1.info()
df1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            124 non-null    float64
 5   1961            126 non-null    float64
 6   1962            127 non-null    float64
 7   1963            127 non-null    float64
 8   1964            127 non-null    float64
 9   1965            139 non-null    float64
 10  1966            142 non-null    float64
 11  1967            145 non-null    float64
 12  1968            150 non-null    float64
 13  1969            150 non-null    float64
 14  1970            159 non-null    float64
 15  1971            162 non-null    float64
 16  1972            162 non-null    float64
 17  1973            162 non-null    float64
 18  1974            163 non-null    float64
 19  1975            165 non-null    float64
 20  1976            167 non-null    float64
 21  1977            170 non-null    float64
 22  1978            169 non-null    float64
 23  1979            170 non-null    float64
 24  1980            183 non-null    float64
 25  1981            186 non-null    float64
 26  1982            188 non-null    float64
 27  1983            190 non-null    float64
 28  1984            193 non-null    float64
 29  1985            195 non-null    float64
 30  1986            197 non-null    float64
 31  1987            201 non-null    float64
 32  1988            207 non-null    float64
 33  1989            211 non-null    float64
 34  1990            226 non-null    float64
 35  1991            225 non-null    float64
 36  1992            228 non-null    float64
 37  1993            230 non-null    float64
 38  1994            232 non-null    float64
 39  1995            241 non-null    float64
 40  1996            241 non-null    float64
 41  1997            241 non-null    float64
 42  1998            242 non-null    float64
 43  1999            243 non-null    float64
 44  2000            247 non-null    float64
 45  2001            249 non-null    float64
 46  2002            254 non-null    float64
 47  2003            254 non-null    float64
 48  2004            254 non-null    float64
 49  2005            254 non-null    float64
 50  2006            255 non-null    float64
 51  2007            255 non-null    float64
 52  2008            256 non-null    float64
 53  2009            256 non-null    float64
 54  2010            257 non-null    float64
 55  2011            260 non-null    float64
 56  2012            258 non-null    float64
 57  2013            259 non-null    float64
 58  2014            260 non-null    float64
 59  2015            258 non-null    float64
 60  2016            258 non-null    float64
 61  2017            258 non-null    float64
 62  2018            258 non-null    float64
 63  2019            258 non-null    float64
 64  2020            257 non-null    float64
 65  2021            255 non-null    float64
 66  2022            242 non-null    float64
 67  2023            0 non-null      float64
 68  Unnamed: 68     0 non-null      float64
dtypes: float64(65), object(4)
memory usage: 143.5+ KB

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.055866e+08,4.877095e+08,5.966480e+08,6.955307e+08,7.648045e+08,8.720670e+08,9.586592e+08,1.083240e+09,1.245810e+09,1.320670e+09,1.379888e+09,1.531844e+09,1.665363e+09,1.722905e+09,1.873453e+09,1.896457e+09,1.961844e+09,2.044112e+09,2.254831e+09,2.360017e+09,2.469783e+09,2.677641e+09,2.843025e+09,2.553793e+09,2.453597e+09,2.637859e+09,2.615208e+09,2.727850e+09,2.790850e+09,2.962907e+09,2.983635e+09,3.092429e+09,3.276184e+09,3.395799e+09,2.558906e+09,3.103184e+09,3.544708e+09,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.506239e+10,9.458036e+10,1.056384e+11,1.256742e+11,1.664987e+11,1.736982e+11,1.641374e+11,1.751336e+11,1.627753e+11,1.358148e+11,1.533905e+11,1.866213e+11,2.056652e+11,2.186085e+11,2.547097e+11,2.756612e+11,2.402447e+11,2.383869e+11,2.411923e+11,2.708525e+11,2.690311e+11,2.841058e+11,2.673247e+11,2.637117e+11,2.854443e+11,2.602556e+11,2.671800e+11,3.549579e+11,4.414223e+11,5.150003e+11,5.787155e+11,6.641938e+11,7.119016e+11,7.168803e+11,8.518834e+11,9.482788e+11,9.544170e+11,9.633398e+11,9.796905e+11,8.992556e+11,8.297383e+11,9.399593e+11,1.012521e+12,1.006191e+12,9.288802e+11,1.086531e+12,1.185138e+12,NaN,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,1.373333e+09,1.408889e+09,1.748887e+09,1.831109e+09,1.595555e+09,1.733333e+09,2.155555e+09,2.366667e+09,2.555556e+09,2.953333e+09,3.300000e+09,3.697940e+09,3.641723e+09,3.478788e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.825701e+09,4.520947e+09,5.224897e+09,6.203256e+09,6.971758e+09,9.747886e+09,1.010930e+10,1.241615e+10,1.585667e+10,1.780510e+10,1.990733e+10,2.014642e+10,2.049713e+10,1.913422e+10,1.811657e+10,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426650e+10,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.041165e+10,1.113592e+10,1.195171e+10,1.268581e+10,1.384900e+10,1.487476e+10,1.584558e+10,1.442849e+10,1.488050e+10,1.688228e+10,2.350496e+10,2.084333e+10,2.526946e+10,3.184115e+10,4.421533e+10,5.144531e+10,6.212999e+10,6.531603e+10,7.120053e+10,8.862933e+10,1.120323e+11,2.110059e+11,1.871654e+11,1.381169e+11,1.142639e+11,1.165085e+11,1.075070e+11,1.102817e+11,1.089447e+11,1.017701e+11,1.218036e+11,1.279390e+11,1.225760e+11,1.279809e+11,1.331435e+11,2.056871e+11,2.612621e+11,2.743770e+11,2.949498e+11,1.372925e+11,1.401328e+11,1.475247e+11,1.765886e+11,2.044550e+11,2.534537e+11,3.100707e+11,3.960770e+11,4.656273e+11,5.678534e+11,5.084925e+11,5.986075e+11,6.821761e+11,7.377395e+11,8.340970e+11,8.945050e+11,7.692632e+11,6.921149e+11,6.856303e+11,7.681582e+11,8.234056e+11,7.869624e+11,8.449275e+11,8.753937e+11,NaN,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.934074e+09,5.553824e+09,5.553824e+09,5.787824e+09,6.135166e+09,7.558613e+09,7.076794e+09,8.089279e+09,8.775116e+09,1.020792e+10,1.123628e+10,1.040119e+10,8.307827e+09,6.084689e+09,4.438321e+09,5.538749e+09,6.535435e+09,7.675413e+09,6.506381e+09,6.152923e+09,9.129595e+09,8.936079e+09,1.528559e+10,1.781270e+10,2.355206e+10,3.697090e+10,5.238103e+10,6.526642e+10,8.853866e+10,7.030720e+10,8.379947e+10,1.117897e+11,1.280529e+11,1.323391e+11,1.359668e+11,9.049642e+10,5.276162e+10,7.369016e+10,7.945069e+10,7.089796e+10,4.850156e+10,6.650513e+10,1.067828e+11,NaN,NaN

In [3]:
# Inspecting for missing values in the dataset
df1.isna().sum()

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              142
1961              140
1962              139
1963              139
1964              139
1965              127
1966              124
1967              121
1968              116
1969              116
1970              107
1971              104
1972              104
1973              104
1974              103
1975              101
1976               99
1977               96
1978               97
1979               96
1980               83
1981               80
1982               78
1983               76
1984               73
1985               71
1986               69
1987               65
1988               59
1989               55
1990               40
1991               41
1992               38
1993               36
1994               34
1995               25
1996               25
1997               25
1998               24
1999               23
2000               19
2001               17
2002               12
2003               12
2004               12
2005               12
2006               11
2007               11
2008               10
2009               10
2010                9
2011                6
2012                8
2013                7
2014                6
2015                8
2016                8
2017                8
2018                8
2019                8
2020                9
2021               11
2022               24
2023              266
Unnamed: 68       266
dtype: int64

In [4]:
# Inspecting for labelling errors via unique values in each column
cols1 = list(df1.columns)

for col in cols1:
    nUnq = df1[col].nunique()  # Calculate number of unique values for each column
    uValues = df1[col].unique()[:5]  # Retrieve the first 5 unique values for each column
    print([col, nUnq, uValues.tolist() if isinstance(uValues, np.ndarray) else uValues])

['Country Name', 266, ['Aruba', 'Africa Eastern and Southern', 'Afghanistan', 'Africa Western and Central', 'Angola']]
['Country Code', 266, ['ABW', 'AFE', 'AFG', 'AFW', 'AGO']]
['Indicator Name', 1, ['GDP (current US$)']]
['Indicator Code', 1, ['NY.GDP.MKTP.CD']]
['1960', 122, [nan, 537777811.111111, 10411646287.3058, 18606562977.0501, 6592693841.18495]]
['1961', 125, [nan, 548888895.555556, 11135924727.9409, 19682883149.2613, 7311749633.36229]]
['1962', 126, [nan, 546666677.777778, 11951712282.0428, 19922563187.6101, 7756110210.11966]]
['1963', 125, [nan, 751111191.111111, 12685805889.8937, 21539843446.375, 8374175257.73075]]
['1964', 127, [nan, 800000044.444444, 13848998668.6184, 23801123808.1798, 9169983885.71185]]
['1965', 137, [nan, 1006666637.77778, 14874755833.5382, 25976164156.1863, 9994070615.85997]]
['1966', 141, [nan, 1399999966.66667, 15845575303.2224, 27307844369.2551, 10887682273.1014]]
['1967', 144, [nan, 1673333417.77778, 14428492961.8549, 30442724870.836, 11579431668.9165]]
['1968', 148, [nan, 1373333366.66667, 14880501861.1181, 35103499571.7253, 32714085234.2536]]
['1969', 148, [nan, 1408888922.22222, 16882284662.3657, 38250554132.4266, 36683365869.3385]]
['1970', 159, [nan, 1748886595.55556, 23504960311.9234, 78617711.0965325, 43246684072.5906]]
['1971', 161, [nan, 1831108971.11111, 20843326170.6302, 89406608.1458151, 49981023863.9518]]
['1972', 162, [nan, 1595555475.55556, 25269456358.5288, 113414397.365635, 59594466405.9604]]
['1973', 161, [nan, 1733333264.44444, 31841146881.8575, 150841639.297444, 75616081942.3622]]
['1974', 161, [nan, 2155555497.77778, 44215328355.8688, 186557081.998137, 143724627345.905]]
['1975', 163, [nan, 2366666615.55556, 51445309626.4799, 220112572.205331, 158823244910.068]]
['1976', 165, [nan, 85062389705.6863, 2555555566.66667, 62129985410.0664, 227283850.831271]]
['1977', 168, [nan, 94580364409.6732, 2953333417.77778, 65316034540.7121, 253997897.226968]]
['1978', 167, [nan, 105638428409.89, 3300000108.88889, 71200526845.3747, 308020261.164149]]
['1979', 169, [nan, 125674232672.796, 3697940409.61098, 88629333635.7157, 411548748.354729]]
['1980', 181, [nan, 166498714766.889, 3641723321.99546, 112032331232.328, 5934073603.67893]]
['1981', 185, [nan, 173698197940.94, 3478787909.09091, 211005911802.917, 5553824463.8796]]
['1982', 187, [nan, 164137396908.864, 187165406370.026, 5553824463.8796, 375914743.581006]]
['1983', 188, [nan, 175133555078.419, 138116898441.305, 5787823808.69565, 327850042.515872]]
['1984', 191, [nan, 162775275752.795, 114263904328.182, 6135166254.1806, 1857337995.338]]
['1985', 194, [nan, 135814811984.368, 116508527443.662, 7558613008.02675, 1897050116.55012]]
['1986', 195, [405586592.178771, 153390484188.949, nan, 107507001440.375, 7076793822.74247]]
['1987', 199, [487709497.206704, 186621266271.16, nan, 110281682790.499, 8089279284.61538]]
['1988', 205, [596648044.692737, 205665163136.019, nan, 108944735237.174, 8775116269.23077]]
['1989', 209, [695530726.256983, 218608488618.471, nan, 101770140749.657, 10207922517.0569]]
['1990', 225, [764804469.273743, 254709710985.787, nan, 121803568895.987, 11236275842.8094]]
['1991', 223, [872067039.106145, 275661199882.418, nan, 127939039832.689, 10401188707.2808]]
['1992', 226, [958659217.877095, 240244722741.314, nan, 122575953686.486, 8307826847.39834]]
['1993', 229, [1083240223.46369, 238386938825.711, nan, 127980941949.696, 6084688935.80032]]
['1994', 230, [1245810055.86592, 241192309586.531, nan, 133143476720.137, 4438321017.39068]]
['1995', 239, [1320670391.06145, 270852456563.177, nan, 205687093879.591, 5538749259.94714]]
['1996', 239, [1379888268.15642, 269031138302.621, nan, 261262106172.312, 6535434716.00224]]
['1997', 240, [1531843575.41899, 284105790703.825, nan, 274376968923.496, 7675412600.66513]]
['1998', 240, [1665363128.49162, 267324683725.004, nan, 294949797405.741, 6506381416.53236]]
['1999', 241, [1722905027.93296, 263711675511.042, nan, 137292485423.693, 6152922942.24539]]
['2000', 246, [1873452513.96648, 285444334460.283, nan, 140132777859.081, 9129594815.57661]]
['2001', 247, [1896456983.24022, 260255606088.705, nan, 147524718751.249, 8936079251.42093]]
['2002', 252, [1961843575.41899, 267180041538.394, 3825701405.51958, 176588559103.843, 15285592486.2532]]
['2003', 253, [2044111731.84358, 354957861044.465, 4520946849.32079, 204455023741.489, 17812704627.0282]]
['2004', 253, [2254830726.25698, 441422327909.38, 5224896718.67782, 253453654650.339, 23552057820.4599]]
['2005', 252, [2360017318.43575, 515000281378.357, 6203256497.09044, 310070743908.926, 36970901023.7893]]
['2006', 253, [2469782681.56425, 578715537772.906, 6971758332.88917, 396077046021.055, 52381025102.321]]
['2007', 253, [2677641340.78212, 664193791807.554, 9747886104.53251, 465627259599.126, 65266415706.9741]]
['2008', 254, [2843024581.00559, 711901639869.787, 10109296957.6569, 567853448132.047, 88538664884.265]]
['2009', 254, [2553793296.08939, 716880259519.984, 12416152648.0573, 508492534468.294, 70307196474.1272]]
['2010', 255, [2453597206.70391, 851883418283.708, 15856668496.388, 598607469639.526, 83799473759.7201]]
['2011', 258, [2637859217.87709, 948278838817.619, 17805098367.2952, 682176065823.115, 111789747670.59]]
['2012', 256, [2615208379.88827, 954417031995.253, 19907329905.9776, 737739503299.735, 128052915202.989]]
['2013', 257, [2727849720.67039, 963339809123.236, 20146416876.3886, 834097010134.991, 132339108708.408]]
['2014', 258, [2790849720.67039, 979690460650.612, 20497128600.3363, 894505003403.491, 135966802156.542]]
['2015', 256, [2962907262.56983, 899255563488.782, 19134221744.5294, 769263195356.949, 90496420626.179]]
['2016', 256, [2983635195.53073, 829738293632.424, 18116572399.1298, 692114931613.254, 52761617225.9253]]
['2017', 256, [3092429050.27933, 939959327939.346, 18753456506.5708, 685630289666.515, 73690155046.555]]
['2018', 256, [3276184357.5419, 1012521425296.35, 18053222734.8881, 768158194632.397, 79450688232.0011]]
['2019', 256, [3395798882.68156, 1006191000190.48, 18799444414.5998, 823405580187.913, 70897962712.6213]]
['2020', 256, [2558906303.88098, 928880235176.594, 19955929060.841, 786962436538.391, 48501561230.001]]
['2021', 253, [3103184101.51354, 1086530704900.5, 14266499429.8746, 844927536437.833, 66505129989.243]]
['2022', 240, [3544707788.05664, 1185137703650.99, nan, 875393693658.084, 106782770714.619]]
['2023', 0, [nan]]
['Unnamed: 68', 0, [nan]]

In [5]:
# Replacing missing values with zero
df1.fillna(0, inplace=True)

# Dropping unnecessary columns
df1.drop (columns=["Indicator Name", "Indicator Code", "Unnamed: 68"], inplace = True)
df1.head()

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.055866e+08,4.877095e+08,5.966480e+08,6.955307e+08,7.648045e+08,8.720670e+08,9.586592e+08,1.083240e+09,1.245810e+09,1.320670e+09,1.379888e+09,1.531844e+09,1.665363e+09,1.722905e+09,1.873453e+09,1.896457e+09,1.961844e+09,2.044112e+09,2.254831e+09,2.360017e+09,2.469783e+09,2.677641e+09,2.843025e+09,2.553793e+09,2.453597e+09,2.637859e+09,2.615208e+09,2.727850e+09,2.790850e+09,2.962907e+09,2.983635e+09,3.092429e+09,3.276184e+09,3.395799e+09,2.558906e+09,3.103184e+09,3.544708e+09,0.0
1,Africa Eastern and Southern,AFE,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.506239e+10,9.458036e+10,1.056384e+11,1.256742e+11,1.664987e+11,1.736982e+11,1.641374e+11,1.751336e+11,1.627753e+11,1.358148e+11,1.533905e+11,1.866213e+11,2.056652e+11,2.186085e+11,2.547097e+11,2.756612e+11,2.402447e+11,2.383869e+11,2.411923e+11,2.708525e+11,2.690311e+11,2.841058e+11,2.673247e+11,2.637117e+11,2.854443e+11,2.602556e+11,2.671800e+11,3.549579e+11,4.414223e+11,5.150003e+11,5.787155e+11,6.641938e+11,7.119016e+11,7.168803e+11,8.518834e+11,9.482788e+11,9.544170e+11,9.633398e+11,9.796905e+11,8.992556e+11,8.297383e+11,9.399593e+11,1.012521e+12,1.006191e+12,9.288802e+11,1.086531e+12,1.185138e+12,0.0
2,Afghanistan,AFG,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,1.373333e+09,1.408889e+09,1.748887e+09,1.831109e+09,1.595555e+09,1.733333e+09,2.155555e+09,2.366667e+09,2.555556e+09,2.953333e+09,3.300000e+09,3.697940e+09,3.641723e+09,3.478788e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.825701e+09,4.520947e+09,5.224897e+09,6.203256e+09,6.971758e+09,9.747886e+09,1.010930e+10,1.241615e+10,1.585667e+10,1.780510e+10,1.990733e+10,2.014642e+10,2.049713e+10,1.913422e+10,1.811657e+10,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426650e+10,0.000000e+00,0.0
3,Africa Western and Central,AFW,1.041165e+10,1.113592e+10,1.195171e+10,1.268581e+10,1.384900e+10,1.487476e+10,1.584558e+10,1.442849e+10,1.488050e+10,1.688228e+10,2.350496e+10,2.084333e+10,2.526946e+10,3.184115e+10,4.421533e+10,5.144531e+10,6.212999e+10,6.531603e+10,7.120053e+10,8.862933e+10,1.120323e+11,2.110059e+11,1.871654e+11,1.381169e+11,1.142639e+11,1.165085e+11,1.075070e+11,1.102817e+11,1.089447e+11,1.017701e+11,1.218036e+11,1.279390e+11,1.225760e+11,1.279809e+11,1.331435e+11,2.056871e+11,2.612621e+11,2.743770e+11,2.949498e+11,1.372925e+11,1.401328e+11,1.475247e+11,1.765886e+11,2.044550e+11,2.534537e+11,3.100707e+11,3.960770e+11,4.656273e+11,5.678534e+11,5.084925e+11,5.986075e+11,6.821761e+11,7.377395e+11,8.340970e+11,8.945050e+11,7.692632e+11,6.921149e+11,6.856303e+11,7.681582e+11,8.234056e+11,7.869624e+11,8.449275e+11,8.753937e+11,0.0
4,Angola,AGO,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.934074e+09,5.553824e+09,5.553824e+09,5.787824e+09,6.135166e+09,7.558613e+09,7.076794e+09,8.089279e+09,8.775116e+09,1.020792e+10,1.123628e+10,1.040119e+10,8.307827e+09,6.084689e+09,4.438321e+09,5.538749e+09,6.535435e+09,7.675413e+09,6.506381e+09,6.152923e+09,9.129595e+09,8.936079e+09,1.528559e+10,1.781270e+10,2.355206e+10,3.697090e+10,5.238103e+10,6.526642e+10,8.853866e+10,7.030720e+10,8.379947e+10,1.117897e+11,1.280529e+11,1.323391e+11,1.359668e+11,9.049642e+10,5.276162e+10,7.369016e+10,7.945069e+10,7.089796e+10,4.850156e+10,6.650513e+10,1.067828e+11,0.0

In [6]:
# Save to CSV

df1.to_csv('API_NY.GDP.MKTP.CD_DS2_CLEANED.csv', index=False)

##### 2nd

In [7]:
df2 = pd.read_csv("Metadata_Country_API_NY.GDP.MKTP.CD_DS2_en_csv_v2_581470.csv")
df2.info()
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Code  265 non-null    object
 1   Region        217 non-null    object
 2   IncomeGroup   216 non-null    object
 3   SpecialNotes  126 non-null    object
 4   TableName     265 non-null    object
 5   Unnamed: 5    0 non-null      float64
dtypes: float64(1), object(5)
memory usage: 12.6+ KB

,Country Code,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
0,ABW,Latin America & Caribbean,High income,NaN,Aruba,NaN
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern,NaN
2,AFG,South Asia,Low income,The reporting period for national accounts dat...,Afghanistan,NaN
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central,NaN
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola,NaN

In [8]:
# Inspecting for missing values in the dataset
df2.isna().sum()

Country Code      0
Region           48
IncomeGroup      49
SpecialNotes    139
TableName         0
Unnamed: 5      265
dtype: int64

In [9]:
# Inspecting for labelling errors via unique values in each column
cols2 = list(df2.columns)

for col in cols2:
    nUnq = df2[col].nunique()  # Calculate number of unique values for each column
    uValues = df2[col].unique()[:10]  # Retrieve the first 10 unique values for each column
    print([col, nUnq, uValues.tolist() if isinstance(uValues, np.ndarray) else uValues])

['Country Code', 265, ['ABW', 'AFE', 'AFG', 'AFW', 'AGO', 'ALB', 'AND', 'ARB', 'ARE', 'ARG']]
['Region', 7, ['Latin America & Caribbean', nan, 'South Asia', 'Sub-Saharan Africa', 'Europe & Central Asia', 'Middle East & North Africa', 'East Asia & Pacific', 'North America']]
['IncomeGroup', 4, ['High income', nan, 'Low income', 'Lower middle income', 'Upper middle income']]
['SpecialNotes', 111, [nan, '26 countries, stretching from the Red Sea in the North to the Cape of Good Hope in the South (https://www.worldbank.org/en/region/afr/eastern-and-southern-africa)', 'The reporting period for national accounts data is designated as either calendar year basis (CY) or fiscal year basis (FY). For this country, it is fiscal year-based (fiscal year-end: March 20). Also, an estimate (PA.NUS.ATLS) of the exchange rate covers the same period and thus differs from the official exchange rate (CY).\n\nIn addition, the World Bank systematically assesses the appropriateness of official exchange rates as conversion factors. In this country, multiple or dual exchange rate activity exists and must be accounted for appropriately in underlying statistics. An alternative estimate (“alternative conversion factor” - PA.NUS.ATLS) is thus calculated as a weighted average of the different exchange rates in use in the country. Doing so better reflects economic reality and leads to more accurate cross-country comparisons and country classifications by income level. For this country, this applies to the period 1960-2006. Alternative conversion factors are used in the Atlas methodology and elsewhere in World Development Indicators as single-year conversion factors.', '22 countries, stretching from the westernmost point of Africa, across the equator, and partly along the Atlantic Ocean till the Republic of Congo in the South (https://www.worldbank.org/en/region/afr/western-and-central-africa)', 'The World Bank systematically assesses the appropriateness of official exchange rates as conversion factors. In this country, multiple or dual exchange rate activity exists and must be accounted for appropriately in underlying statistics. An alternative estimate (“alternative conversion factor” - PA.NUS.ATLS) is thus calculated as a weighted average of the different exchange rates in use in the country. Doing so better reflects economic reality and leads to more accurate cross-country comparisons and country classifications by income level. For this country, this applies to the period 1994-2022. Alternative conversion factors are used in the Atlas methodology and elsewhere in World Development Indicators as single-year conversion factors.', 'Arab World aggregate. Arab World is composed of members of the League of Arab States.', 'The World Bank systematically assesses the appropriateness of official exchange rates as conversion factors. In this country, multiple or dual exchange rate activity exists and must be accounted for appropriately in underlying statistics. An alternative estimate (“alternative conversion factor” - PA.NUS.ATLS) is thus calculated as a weighted average of the different exchange rates in use in the country. Doing so better reflects economic reality and leads to more accurate cross-country comparisons and country classifications by income level. For this country, this applies to the period 1971-2018. Alternative conversion factors are used in the Atlas methodology and elsewhere in World Development Indicators as single-year conversion factors.', 'The reporting period for national accounts data is designated as either calendar year basis (CY) or fiscal year basis (FY). For this country, it is fiscal year-based (fiscal year-end: June 30). Also, an estimate (PA.NUS.ATLS) of the exchange rate covers the same period and thus differs from the official exchange rate (CY).', 'A simple multiplier is used to convert the national currencies of EMU members to euros. The following irrevocable euro conversion rate was adopted by the EU Council on January 1, 1999: 1 euro = 13.7603 Austrian schilling. Please note that historical data before 1999 are not actual euros and are not comparable or suitable for aggregation across countries.', 'The World Bank systematically assesses the appropriateness of official exchange rates as conversion factors. In this country, multiple or dual exchange rate activity exists and must be accounted for appropriately in underlying statistics. An alternative estimate (“alternative conversion factor” - PA.NUS.ATLS) is thus calculated as a weighted average of the different exchange rates in use in the country. Doing so better reflects economic reality and leads to more accurate cross-country comparisons and country classifications by income level. For this country, this applies to the period 1983-2022. Alternative conversion factors are used in the Atlas methodology and elsewhere in World Development Indicators as single-year conversion factors.']]
['TableName', 265, ['Aruba', 'Africa Eastern and Southern', 'Afghanistan', 'Africa Western and Central', 'Angola', 'Albania', 'Andorra', 'Arab World', 'United Arab Emirates', 'Argentina']]
['Unnamed: 5', 0, [nan]]

In [10]:
# Replacing missing values
df2['Region'].fillna('Unknown', inplace=True)
df2['IncomeGroup'].fillna('Unknown', inplace=True)

# Dropping unnecessary columns
df2.drop (columns=["SpecialNotes", "Unnamed: 5"], inplace = True)

# Rename 'TableName' column to 'Country Name'
df2.rename(columns={'TableName': 'Country Name'}, inplace=True)

df2.head()

,Country Code,Region,IncomeGroup,Country Name
0,ABW,Latin America & Caribbean,High income,Aruba
1,AFE,Unknown,Unknown,Africa Eastern and Southern
2,AFG,South Asia,Low income,Afghanistan
3,AFW,Unknown,Unknown,Africa Western and Central
4,AGO,Sub-Saharan Africa,Lower middle income,Angola

In [11]:
# Save to CSV

df2.to_csv('Metadata_Country_API_NY.GDP.MKTP.CD_DS2_CLEANED.csv', index=False)

##### 3rd

In [3]:
df3 = pd.read_excel("inward_remittance_flows_december_2023_1.xlsx")
df3.info()
df3.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Remittance inflows (US$ million)  224 non-null    object
 1   2000                              199 non-null    float64
 2   2001                              199 non-null    float64
 3   2002                              199 non-null    float64
 4   2003                              199 non-null    float64
 5   2004                              199 non-null    float64
 6   2005                              199 non-null    float64
 7   2006                              199 non-null    float64
 8   2007                              198 non-null    float64
 9   2008                              198 non-null    float64
 10  2009                              198 non-null    float64
 11  2010                              198 non-null    float64
 12  2011                              197 non-null    float64
 13  2012                              197 non-null    float64
 14  2013                              197 non-null    float64
 15  2014                              197 non-null    float64
 16  2015                              197 non-null    float64
 17  2016                              197 non-null    float64
 18  2017                              196 non-null    float64
 19  2018                              196 non-null    float64
 20  2019                              196 non-null    float64
 21  2020                              196 non-null    float64
 22  2021                              196 non-null    float64
 23  2022                              196 non-null    float64
 24  2023e                             196 non-null    float64
 25  % of GDP in 2023                  190 non-null    float64
dtypes: float64(25), object(1)
memory usage: 46.0+ KB

,Remittance inflows (US$ million),2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023e,% of GDP in 2023
0,Afghanistan,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,89.500000,140.695166,378.206657,179.116561,219.416087,347.165292,253.367822,348.624717,627.710802,822.731630,803.546454,828.571904,788.917115,320.000000,370.000000,300.0,2.007898
1,Albania,597.8,699.3,733.57,888.748582,1160.672105,1289.704316,1359.467325,1468.020000,1865.600000,1717.698012,1586.574271,1552.078514,1419.772515,1281.848114,1421.007454,1290.863508,1306.009167,1311.822432,1458.210056,1472.812242,1465.987212,1718.355918,1745.245136,1970.0,8.553317
2,Algeria,0.0,0.0,0.00,0.000000,0.000000,170.000000,189.000000,99.004563,103.631887,150.336961,196.600000,202.869816,214.841269,209.601443,2452.442617,1997.393458,1989.023597,1791.887073,1984.998399,1785.838683,1699.608935,1792.158957,1658.975810,1770.0,0.790179
3,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.100000,47.416324,53.001418,0.000000,0.0,0.000000

In [4]:
# Inspecting for missing values in the dataset
df3.isna().sum()

Remittance inflows (US$ million)     2
2000                                27
2001                                27
2002                                27
2003                                27
2004                                27
2005                                27
2006                                27
2007                                28
2008                                28
2009                                28
2010                                28
2011                                29
2012                                29
2013                                29
2014                                29
2015                                29
2016                                29
2017                                30
2018                                30
2019                                30
2020                                30
2021                                30
2022                                30
2023e                               30
% of GDP in 2023                    36
dtype: int64

In [5]:
# Inspecting for labelling errors via unique values in each column
cols3 = list(df3.columns)

for col in cols3:
    nUnq = df3[col].nunique()  # Calculate number of unique values for each column
    uValues = df3[col].unique()[:5]  # Retrieve the first 5 unique values for each column
    print([col, nUnq, uValues.tolist() if isinstance(uValues, np.ndarray) else uValues])

['Remittance inflows (US$ million)', 224, ['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra']]
[2000, 138, [0.0, 597.8, nan, 17.342962962962964, 86.34365858988221]]
[2001, 142, [0.0, 699.3, nan, 23.676666666666666, 189.6]]
[2002, 150, [0.0, 733.5699999999999, nan, 14.242166666666666, 206.63]]
[2003, 152, [0.0, 888.748582309638, nan, 16.372237037037035, 273.42]]
[2004, 156, [0.0, 1160.6721050195456, nan, 17.601625925925923, 311.78]]
[2005, 169, [0.0, 1289.7043159261334, 169.99999999999272, nan, 18.30548888888889]]
[2006, 173, [0.0, 1359.46732466364, 189.00000000000816, nan, 19.32572037037037]]
[2007, 175, [0.0, 1468.02, 99.00456334764347, nan, 20.783287037037034]]
[2008, 177, [89.5, 1865.6000000000001, 103.63188721222971, nan, 0.0]]
[2009, 180, [140.69516629999998, 1717.6980121651357, 150.3369614945351, nan, 0.0]]
[2010, 182, [378.2066570180999, 1586.5742713564164, 196.60000000000002, nan, 0.0]]
[2011, 184, [179.1165613764, 1552.0785143403584, 202.86981618834116, nan, 0.0]]
[2012, 184, [219.4160874814624, 1419.7725154302648, 214.8412686354578, nan, 0.0]]
[2013, 183, [347.1652918141468, 1281.8481137530773, 209.6014434446368, nan, 0.0]]
[2014, 186, [253.3678216033428, 1421.0074543659491, 2452.4426170725615, nan, 0.0]]
[2015, 186, [348.6247173026476, 1290.8635080940198, 1997.3934583539626, nan, 0.0]]
[2016, 187, [627.7108023773859, 1306.0091669250385, 1989.0235971229508, nan, 0.0]]
[2017, 187, [822.7316302455583, 1311.8224321379964, 1791.8870732862547, nan, 0.0]]
[2018, 188, [803.5464537865573, 1458.2100558531142, 1984.9983991317279, nan, 0.0]]
[2019, 189, [828.5719041111796, 1472.8122416103738, 1785.838683222985, nan, 21.1]]
[2020, 191, [788.9171152452299, 1465.9872124909666, 1699.6089346251986, nan, 47.416323738830535]]
[2021, 191, [320.0, 1718.3559183217922, 1792.158957014779, nan, 53.001417773052474]]
[2022, 190, [370.0, 1745.2451357665093, 1658.975809673424, nan, 0.0]]
['2023e', 181, [300.0, 1970.0, 1770.0, nan, 0.0]]
['% of GDP in 2023', 186, [2.007897731075564, 8.553317124001389, 0.7901785714285714, nan, 0.0]]

In [12]:
# Replacing missing values
df3.fillna(df3.mean(numeric_only=True), inplace=True)

# Rename '2023e' column to '2023'
df3.rename(columns={'2023e': '2023'}, inplace=True)
df3.head()

,Remittance inflows (US$ million),2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,% of GDP in 2023
0,Afghanistan,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,89.500000,140.695166,378.206657,179.116561,219.416087,347.165292,253.367822,348.624717,627.710802,822.731630,803.546454,828.571904,788.917115,320.000000,370.000000,300.000000,2.007898
1,Albania,597.800000,699.300000,733.570000,888.748582,1160.672105,1289.704316,1359.467325,1468.020000,1865.600000,1717.698012,1586.574271,1552.078514,1419.772515,1281.848114,1421.007454,1290.863508,1306.009167,1311.822432,1458.210056,1472.812242,1465.987212,1718.355918,1745.245136,1970.000000,8.553317
2,Algeria,0.000000,0.000000,0.000000,0.000000,0.000000,170.000000,189.000000,99.004563,103.631887,150.336961,196.600000,202.869816,214.841269,209.601443,2452.442617,1997.393458,1989.023597,1791.887073,1984.998399,1785.838683,1699.608935,1792.158957,1658.975810,1770.000000,0.790179
3,American Samoa,1564.610287,1725.502021,2039.947093,2498.910963,2884.183994,3816.930193,4418.041568,5366.990961,6245.927757,5921.371540,6458.847403,7292.041188,7583.320504,8031.766793,8419.121613,8295.530615,8204.286148,8958.880623,9755.177868,10207.493439,10076.742973,11139.022810,11816.166942,12192.988091,5.320881
4,Andorra,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.100000,47.416324,53.001418,0.000000,0.000000,0.000000

In [13]:
# Save to Excel

df3.to_excel('inward_remittance_flows_december_2023_1_CLEANED.xlsx', index=False)

##### 4th

In [2]:
df4 = pd.read_excel("outward-remittance-flows-brief-39-december-2023-revised-as-of-mar.8-2024_1.xlsx", skiprows=1)
df4.info()
df4.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 0 to 222
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Remittance outflows (US$ million)  222 non-null    object
 1   2000                               201 non-null    float64
 2   2001                               201 non-null    float64
 3   2002                               201 non-null    float64
 4   2003                               201 non-null    float64
 5   2004                               201 non-null    float64
 6   2005                               201 non-null    float64
 7   2006                               201 non-null    float64
 8   2007                               201 non-null    float64
 9   2008                               201 non-null    float64
 10  2009                               201 non-null    float64
 11  2010                               201 non-null    float64
 12  2011                               201 non-null    float64
 13  2012                               201 non-null    float64
 14  2013                               201 non-null    float64
 15  2014                               201 non-null    float64
 16  2015                               201 non-null    float64
 17  2016                               201 non-null    float64
 18  2017                               201 non-null    float64
 19  2018                               201 non-null    float64
 20  2019                               201 non-null    float64
 21  2020                               201 non-null    float64
 22  2021                               201 non-null    float64
 23  2022                               201 non-null    float64
 24  % of GDP in 2022                   158 non-null    float64
dtypes: float64(24), object(1)
memory usage: 43.7+ KB

,Remittance outflows (US$ million),2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,% of GDP in 2022
0,Afghanistan,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,216.600000,624.996677,788.698417,454.083462,323.642538,444.730790,524.163479,228.991809,167.894464,143.979106,234.618701,217.292318,225.420606,0.000000,0.000000,NaN
1,Albania,0.0,0.0,0.0,4.135728,4.86374,6.511798,26.532132,9.940000,279.700000,229.819782,209.306822,150.855105,215.775644,190.551294,178.722842,153.312400,147.156757,106.330983,114.879337,119.679641,124.630376,140.344310,149.489653,0.783366
2,Algeria,0.0,0.0,0.0,0.000000,0.00000,27.000000,35.000000,48.863733,26.782545,45.702406,28.000000,30.901605,44.242619,38.715810,295.922112,72.128991,76.633496,214.378057,87.006383,81.545365,149.253465,83.259319,60.221598,0.030873
3,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,91.500000,83.804275,70.514091,0.000000,NaN

In [3]:
# Inspecting for missing values in the dataset
df4.isna().sum()

Remittance outflows (US$ million)     1
2000                                 22
2001                                 22
2002                                 22
2003                                 22
2004                                 22
2005                                 22
2006                                 22
2007                                 22
2008                                 22
2009                                 22
2010                                 22
2011                                 22
2012                                 22
2013                                 22
2014                                 22
2015                                 22
2016                                 22
2017                                 22
2018                                 22
2019                                 22
2020                                 22
2021                                 22
2022                                 22
% of GDP in 2022                     65
dtype: int64

In [5]:
# Inspecting for labelling errors via unique values in each column
cols4 = list(df4.columns)

for col in cols4:
    nUnq = df4[col].nunique()  # Calculate number of unique values for each column
    uValues = df4[col].unique()[:5]  # Retrieve the first 5 unique values for each column
    print([col, nUnq, uValues.tolist() if isinstance(uValues, np.ndarray) else uValues])

['Remittance outflows (US$ million)', 222, ['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra']]
['2000', 131, [0.0, nan, 266.29, 1.558148148148148, 267.7]]
['2001', 135, [0.0, nan, 216.06, 1.5644444444444443, 256.09999999999997]]
['2002', 143, [0.0, nan, 223.50795912, 1.4114814814814813, 119.55000000000001]]
['2003', 147, [0.0, 4.13572807, nan, 229.84996999999998, 1.4892925925925926]]
['2004', 150, [0.0, 4.86374036, nan, 296.0095912, 1.5667370370370368]]
['2005', 166, [0.0, 6.5117980461410605, 26.999999999998785, nan, 214.9052159]]
['2006', 169, [0.0, 26.532132030652928, 35.000000000001585, nan, 412.66678497]]
['2007', 171, [0.0, 9.94, 48.86373265194798, nan, 602.6714512799999]]
['2008', 173, [216.60000000000002, 279.7, 26.782545164134874, nan, 0.0]]
['2009', 177, [624.99667679, 229.8197823330384, 45.70240583643372, nan, 0.0]]
['2010', 176, [788.6984168004001, 209.30682156565598, 28.0, nan, 0.0]]
['2011', 180, [454.08346197109995, 150.85510534462838, 30.901604941008035, nan, 0.0]]
['2012', 181, [323.6425382684229, 215.77564388998007, 44.242618918850376, nan, 0.0]]
['2013', 181, [444.73079048332613, 190.5512936434099, 38.715810197915296, nan, 0.0]]
['2014', 184, [524.1634785287775, 178.722842218417, 295.9221121414799, nan, 0.0]]
['2015', 183, [228.9918092151333, 153.31240047805892, 72.12899059293858, nan, 0.0]]
['2016', 182, [167.89446428252646, 147.15675738801244, 76.63349632156572, nan, 0.0]]
['2017', 179, [143.97910623096095, 106.33098291276094, 214.37805673439382, nan, 0.0]]
['2018', 178, [234.61870060052505, 114.87933694313179, 87.00638320505239, nan, 0.0]]
['2019', 179, [217.29231799093785, 119.67964076947914, 81.5453645801962, nan, 91.5]]
['2020', 180, [225.42060647991676, 124.63037566919759, 149.25346526299762, nan, 83.80427498046606]]
['2021', 175, [0.0, 140.34430970129867, 83.25931940874878, nan, 70.51409070292239]]
['2022', 158, [0.0, 149.48965321212165, 60.22159792386957, nan, 517.6681873929803]]
['% of GDP in 2022', 155, [nan, 0.7833655778028699, 0.030873371231349107, 0.42161913275912416, 3.400868375895928]]

In [9]:
# Replacing missing values
df4.fillna(df4.mean(numeric_only=True), inplace=True)

# Rename 'Remittance outflows (US$ million)' column to 'Country Name'
df4.rename(columns={'Remittance outflows (US$ million)': 'Country Name'}, inplace=True)

df4.head()

,Country Name,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,% of GDP in 2022
0,Afghanistan,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,216.600000,624.996677,788.698417,454.083462,323.642538,444.730790,524.163479,228.991809,167.894464,143.979106,234.618701,217.292318,225.420606,0.000000,0.000000,1.638010
1,Albania,0.000000,0.000000,0.000000,4.135728,4.863740,6.511798,26.532132,9.940000,279.700000,229.819782,209.306822,150.855105,215.775644,190.551294,178.722842,153.312400,147.156757,106.330983,114.879337,119.679641,124.630376,140.344310,149.489653,0.783366
2,Algeria,0.000000,0.000000,0.000000,0.000000,0.000000,27.000000,35.000000,48.863733,26.782545,45.702406,28.000000,30.901605,44.242619,38.715810,295.922112,72.128991,76.633496,214.378057,87.006383,81.545365,149.253465,83.259319,60.221598,0.030873
3,American Samoa,619.790688,666.530136,757.872143,827.575449,937.145887,1044.823974,1189.496642,1456.535490,1766.722684,1695.046073,1749.633758,1961.205135,2082.081291,2123.454843,2167.587908,2112.478300,2120.859601,2289.500039,2424.150521,2523.338252,2347.592680,2535.594018,2511.114798,1.638010
4,Andorra,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,91.500000,83.804275,70.514091,0.000000,1.638010

In [10]:
# Save to Excel

df4.to_excel('outward-remittance-flows-brief-39-december-2023_CLEANED.xlsx', index=False)

##### 5th

In [41]:
df5 = pd.read_excel("bilateral_remittance_matrix_2021_0.xlsx", skiprows=1)
df5.info()
df5.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231 entries, 0 to 230
Columns: 216 entries, Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)  to WORLD
dtypes: float64(210), object(6)
memory usage: 389.9+ KB

,Remittance-receiving country (across) - Remittance-sending country (down),Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Aruba,Australia,Austria,Azerbaijan,"Bahamas, The",Bahrain,Bangladesh,Barbados,Belarus,Belgium,Belize,Benin,Bermuda,Bhutan,Bolivia,Bosnia and Herzegovina,Botswana,Brazil,Brunei Darussalam,Bulgaria,Burkina Faso,Burundi,Cabo Verde,Cambodia,Cameroon,Canada,Cayman Islands,Central African Republic,Chad,Channel Islands,Chile,China,Colombia,Comoros,"Congo, Dem. Rep.","Congo, Rep.",Costa Rica,Cote d'Ivoire,Croatia,Cuba,Curacao,Cyprus,Czech Republic,Denmark,Djibouti,Dominica,Dominican Republic,Ecuador,"Egypt, Arab Rep.",El Salvador,Equatorial Guinea,Eritrea,Estonia,Eswatini,Ethiopia,Faeroe Islands,Fiji,Finland,France,French Polynesia,Gabon,"Gambia, The",Georgia,Germany,Ghana,Greece,Greenland,Grenada,Guam,Guatemala,Guinea,Guinea-Bissau,Guyana,Haiti,Honduras,"Hong Kong SAR, China",Hungary,Iceland,India,Indonesia,"Iran, Islamic Rep.",Iraq,Ireland,Isle of Man,Israel,Italy,Jamaica,Japan,Jordan,Kazakhstan,Kenya,Kiribati,"Korea, Dem. Rep.","Korea, Rep.",Kosovo,Kuwait,Kyrgyz Republic,Lao PDR,Latvia,Lebanon,Lesotho,Liberia,Libya,Liechtenstein,Lithuania,Luxembourg,"Macao SAR, China",Madagascar,Malawi,Malaysia,Maldives,Mali,Malta,Marshall Islands,Mauritania,Mauritius,Mexico,"Micronesia, Fed. Sts.",Moldova,Monaco,Mongolia,Montenegro,Morocco,Mozambique,Myanmar,Namibia,Nepal,Netherlands,New Caledonia,New Zealand,Nicaragua,Niger,Nigeria,North Macedonia,Northern Mariana Islands,Norway,Oman,Pakistan,Palau,Panama,Papua New Guinea,Paraguay,Peru,Philippines,Poland,Portugal,Puerto Rico,Qatar,Romania,Russian Federation,Rwanda,Samoa,San Marino,Sao Tome and Principe,Saudi Arabia,Senegal,Serbia,Seychelles,Sierra Leone,Singapore,Sint Maarten (Dutch part),Slovak Republic,Slovenia,Solomon Islands,Somalia,South Africa,South Sudan,Spain,Sri Lanka,St. Kitts and Nevis,St. Lucia,St. Martin (French part),St. Vincent and the Grenadines,Sudan,Suriname,Sweden,Switzerland,Syrian Arab Republic,Tajikistan,Tanzania,Thailand,Timor-Leste,Togo,Tonga,Trinidad and Tobago,Tunisia,Turkey,Turkmenistan,Turks and Caicos Islands,Tuvalu,Uganda,Ukraine,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Vanuatu,"Venezuela, RB",Vietnam,Virgin Islands (U.S.),West Bank and Gaza,"Yemen, Rep.",Zambia,Zimbabwe,WORLD
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,369.301141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.575814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384.876955
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.51408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.258225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.011948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.410091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.352671,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.135354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.682369
2,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.916523,NaN,NaN,NaN,NaN,4.103915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.428221,NaN,1.724884,NaN,NaN,NaN,2.260146,NaN,NaN,11.130318,NaN,NaN,NaN,NaN,NaN,NaN,0.116856,NaN,NaN,NaN,7.037368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.651116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.692849,NaN,NaN,NaN,NaN,3.130261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.290328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.731464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.578799,2.474202,NaN,NaN,NaN,NaN,NaN,NaN,25.82916,NaN,NaN,NaN,79.096411
3,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.518015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.559093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.007639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.01622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.934971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.912611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.495363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.901618,NaN,NaN,NaN,NaN,0.878566,NaN,NaN,NaN,NaN,NaN,38.224096
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.58971,NaN,NaN,0.10475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.24554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.02547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.591044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.145300,NaN,NaN,NaN,NaN,1.962976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.533782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.228307,NaN,NaN,NaN,NaN,0.65266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.017247,NaN,26.184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126.392635,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.491338,0.370118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.840073,0.258499,0.03529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,230.668739

In [42]:
# Rename the first column header to something appropriate
df5.rename(columns={df5.columns[0]: 'Remittance-sending country'}, inplace=True)
df5.info()
df5.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231 entries, 0 to 230
Columns: 216 entries, Remittance-sending country to WORLD
dtypes: float64(210), object(6)
memory usage: 389.9+ KB

,Remittance-sending country,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Aruba,Australia,Austria,Azerbaijan,"Bahamas, The",Bahrain,Bangladesh,Barbados,Belarus,Belgium,Belize,Benin,Bermuda,Bhutan,Bolivia,Bosnia and Herzegovina,Botswana,Brazil,Brunei Darussalam,Bulgaria,Burkina Faso,Burundi,Cabo Verde,Cambodia,Cameroon,Canada,Cayman Islands,Central African Republic,Chad,Channel Islands,Chile,China,Colombia,Comoros,"Congo, Dem. Rep.","Congo, Rep.",Costa Rica,Cote d'Ivoire,Croatia,Cuba,Curacao,Cyprus,Czech Republic,Denmark,Djibouti,Dominica,Dominican Republic,Ecuador,"Egypt, Arab Rep.",El Salvador,Equatorial Guinea,Eritrea,Estonia,Eswatini,Ethiopia,Faeroe Islands,Fiji,Finland,France,French Polynesia,Gabon,"Gambia, The",Georgia,Germany,Ghana,Greece,Greenland,Grenada,Guam,Guatemala,Guinea,Guinea-Bissau,Guyana,Haiti,Honduras,"Hong Kong SAR, China",Hungary,Iceland,India,Indonesia,"Iran, Islamic Rep.",Iraq,Ireland,Isle of Man,Israel,Italy,Jamaica,Japan,Jordan,Kazakhstan,Kenya,Kiribati,"Korea, Dem. Rep.","Korea, Rep.",Kosovo,Kuwait,Kyrgyz Republic,Lao PDR,Latvia,Lebanon,Lesotho,Liberia,Libya,Liechtenstein,Lithuania,Luxembourg,"Macao SAR, China",Madagascar,Malawi,Malaysia,Maldives,Mali,Malta,Marshall Islands,Mauritania,Mauritius,Mexico,"Micronesia, Fed. Sts.",Moldova,Monaco,Mongolia,Montenegro,Morocco,Mozambique,Myanmar,Namibia,Nepal,Netherlands,New Caledonia,New Zealand,Nicaragua,Niger,Nigeria,North Macedonia,Northern Mariana Islands,Norway,Oman,Pakistan,Palau,Panama,Papua New Guinea,Paraguay,Peru,Philippines,Poland,Portugal,Puerto Rico,Qatar,Romania,Russian Federation,Rwanda,Samoa,San Marino,Sao Tome and Principe,Saudi Arabia,Senegal,Serbia,Seychelles,Sierra Leone,Singapore,Sint Maarten (Dutch part),Slovak Republic,Slovenia,Solomon Islands,Somalia,South Africa,South Sudan,Spain,Sri Lanka,St. Kitts and Nevis,St. Lucia,St. Martin (French part),St. Vincent and the Grenadines,Sudan,Suriname,Sweden,Switzerland,Syrian Arab Republic,Tajikistan,Tanzania,Thailand,Timor-Leste,Togo,Tonga,Trinidad and Tobago,Tunisia,Turkey,Turkmenistan,Turks and Caicos Islands,Tuvalu,Uganda,Ukraine,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Vanuatu,"Venezuela, RB",Vietnam,Virgin Islands (U.S.),West Bank and Gaza,"Yemen, Rep.",Zambia,Zimbabwe,WORLD
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,369.301141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.575814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384.876955
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.51408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.258225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.011948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.410091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.352671,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.135354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.682369
2,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.916523,NaN,NaN,NaN,NaN,4.103915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.428221,NaN,1.724884,NaN,NaN,NaN,2.260146,NaN,NaN,11.130318,NaN,NaN,NaN,NaN,NaN,NaN,0.116856,NaN,NaN,NaN,7.037368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.651116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.692849,NaN,NaN,NaN,NaN,3.130261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.290328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.731464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.578799,2.474202,NaN,NaN,NaN,NaN,NaN,NaN,25.82916,NaN,NaN,NaN,79.096411
3,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.518015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.559093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.007639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.01622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.934971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.912611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.495363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.901618,NaN,NaN,NaN,NaN,0.878566,NaN,NaN,NaN,NaN,NaN,38.224096
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.58971,NaN,NaN,0.10475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.24554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.02547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.591044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.145300,NaN,NaN,NaN,NaN,1.962976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.533782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.228307,NaN,NaN,NaN,NaN,0.65266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.017247,NaN,26.184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126.392635,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.491338,0.370118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.840073,0.258499,0.03529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,230.668739

In [39]:
# Inspecting for missing values in the dataset
df5.isna().sum()

Remittance-sending country          5
Afghanistan                       160
Albania                           176
Algeria                           161
American Samoa                    231
Andorra                           231
Angola                            170
Antigua and Barbuda               190
Argentina                         154
Armenia                           169
Aruba                             200
Australia                         127
Austria                           157
Azerbaijan                        178
Bahamas, The                      231
Bahrain                           231
Bangladesh                        151
Barbados                          231
Belarus                           173
Belgium                           152
Belize                            187
Benin                             179
Bermuda                           203
Bhutan                            202
Bolivia                           173
Bosnia and Herzegovina            181
Botswana                          192
Brazil                            148
Brunei Darussalam                 231
Bulgaria                          165
Burkina Faso                      187
Burundi                           182
Cabo Verde                        188
Cambodia                          182
Cameroon                          172
Canada                            108
Cayman Islands                    212
Central African Republic          231
Chad                              231
Channel Islands                   231
Chile                             163
China                              91
Colombia                          164
Comoros                           200
Congo, Dem. Rep.                  161
Congo, Rep.                       231
Costa Rica                        175
Cote d'Ivoire                     171
Croatia                           173
Cuba                              231
Curacao                           231
Cyprus                            185
Czech Republic                    171
Denmark                           158
Djibouti                          202
Dominica                          183
Dominican Republic                168
Ecuador                           175
Egypt, Arab Rep.                  147
El Salvador                       176
Equatorial Guinea                 231
Eritrea                           231
Estonia                           179
Eswatini                          196
Ethiopia                          162
Faeroe Islands                    231
Fiji                              188
Finland                           167
France                            100
French Polynesia                  231
Gabon                             191
Gambia, The                       186
Georgia                           178
Germany                           108
Ghana                             161
Greece                            163
Greenland                         231
Grenada                           188
Guam                              231
Guatemala                         175
Guinea                            177
Guinea-Bissau                     189
Guyana                            179
Haiti                             168
Honduras                          177
Hong Kong SAR, China              194
Hungary                           165
Iceland                           187
India                             102
Indonesia                         143
Iran, Islamic Rep.                231
Iraq                              158
Ireland                           159
Isle of Man                       231
Israel                            159
Italy                             121
Jamaica                           165
Japan                             127
Jordan                            162
Kazakhstan                        171
Kenya                             165
Kiribati                          207
Korea, Dem. Rep.                  231
Korea, Rep.                       141
Kosovo                            209
Kuwait                            175
Kyrgyz Republic                   183
Lao PDR                           190
Latvia                            179
Lebanon                           143
Lesotho                           203
Liberia                           182
Libya                             231
Liechtenstein                     231
Lithuania                         177
Luxembourg                        185
Macao SAR, China                  217
Madagascar                        186
Malawi                            187
Malaysia                          155
Maldives                          197
Mali                              172
Malta                             188
Marshall Islands                  217
Mauritania                        186
Mauritius                         191
Mexico                            160
Micronesia, Fed. Sts.             231
Moldova                           176
Monaco                            231
Mongolia                          192
Montenegro                        192
Morocco                           160
Mozambique                        175
Myanmar                           179
Namibia                           188
Nepal                             167
Netherlands                       132
New Caledonia                     231
New Zealand                       150
Nicaragua                         177
Niger                             182
Nigeria                           137
North Macedonia                   178
Northern Mariana Islands          231
Norway                            167
Oman                              188
Pakistan                          129
Palau                             215
Panama                            174
Papua New Guinea                  196
Paraguay                          180
Peru                              160
Philippines                       128
Poland                            155
Portugal                          151
Puerto Rico                       231
Qatar                             186
Romania                           160
Russian Federation                128
Rwanda                            176
Samoa                             198
San Marino                        231
Sao Tome and Principe             199
Saudi Arabia                      160
Senegal                           166
Serbia                            181
Seychelles                        194
Sierra Leone                      181
Singapore                         231
Sint Maarten (Dutch part)         231
Slovak Republic                   177
Slovenia                          182
Solomon Islands                   207
Somalia                           166
South Africa                      148
South Sudan                       197
Spain                             141
Sri Lanka                         154
St. Kitts and Nevis               193
St. Lucia                         189
St. Martin (French part)          231
St. Vincent and the Grenadines    186
Sudan                             161
Suriname                          187
Sweden                            155
Switzerland                       145
Syrian Arab Republic              231
Tajikistan                        182
Tanzania                          172
Thailand                          150
Timor-Leste                       209
Togo                              181
Tonga                             198
Trinidad and Tobago               171
Tunisia                           170
Turkey                            145
Turkmenistan                      229
Turks and Caicos Islands          231
Tuvalu                            231
Uganda                            173
Ukraine                           154
United Arab Emirates              231
United Kingdom                     91
United States                      77
Uruguay                           172
Uzbekistan                        229
Vanuatu                           205
Venezuela, RB                     231
Vietnam                           160
Virgin Islands (U.S.)             231
West Bank and Gaza                172
Yemen, Rep.                       231
Zambia                            175
Zimbabwe                          173
WORLD                              16
dtype: int64

In [43]:
# Inspecting for labelling errors via unique values in each column
cols5 = list(df5.columns)

for col in cols5:
    nUnq = df5[col].nunique()  # Calculate number of unique values for each column
    uValues = df5[col].unique()[:5]  # Retrieve the first 5 unique values for each column
    print([col, nUnq, uValues.tolist() if isinstance(uValues, np.ndarray) else uValues])

['Remittance-sending country', 226, ['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra']]
['Afghanistan', 71, [nan, 0.00046864662895358135, 4.98223509093453, 3.348376490265342, 0.007961964328761242]]
['Albania', 55, [nan, 0.07729341775452661, 5.141769256771227, 6.922719219663784, 17.394609086894928]]
['Algeria', 70, [nan, 0.08018417583376763, 1.5470093411690744, 1.4614890161884733, 0.039177676696896556]]
['American Samoa', 0, [nan]]
['Andorra', 0, [nan]]
['Angola', 61, [nan, 0.0001753758530108724, 0.01376868697135418, 0.011146855673247006, 0.18876738794137873]]
['Antigua and Barbuda', 41, [nan, 0.04504248488408664, 0.005294316452801474, 0.009130317104114207, 0.12861109883751629]]
['Argentina', 77, [nan, 0.5897099159520229, 18.86064942051549, 1.9191842844412608, 0.09766415904597828]]
['Armenia', 62, [nan, 1.0194469144488885, 3.2007522622567874, 6.877368208889946, 10.059281442401732]]
['Aruba', 30, [nan, 0.0039025163747327548, 0.0009756290936831887, 0.07276543949899349, 0.0031359935697498676]]
['Australia', 99, [nan, 0.10475022616303008, 0.009108715318524354, 0.4190009046521203, 4.03780401625606]]
['Austria', 73, [nan, 6.405521696107624, 99.06792293106258, 0.25497707722370155, 0.35448032687197534]]
['Azerbaijan', 53, [nan, 1.0331722238866217, 2.090366854435567, 16.562325771034605, 0.5614342375872531]]
['Bahamas, The', 0, [nan]]
['Bahrain', 0, [nan]]
['Bangladesh', 80, [nan, 191.8714198728756, 11.101184378207648, 357.53198807372996, 9.390122652423427]]
['Barbados', 0, [nan]]
['Belarus', 57, [nan, 0.22429886214530081, 0.21865018254250246, 1.86262865773776, 1.963692643464885]]
['Belgium', 77, [nan, 6.245539913171178, 14.690596056633076, 214.52071875674918, 87.8448766048207]]
['Belize', 44, [nan, 0.02390333274471645, 0.011372349875520417, 0.20907969240200525, 0.02595338884628169]]
['Benin', 52, [nan, 0.060769499190191485, 0.0537847342350563, 0.9532984568608204, 0.00030714340599269553]]
['Bermuda', 23, [nan, 0.967623983161815, 43.91524231272853, 0.8187587549830744, 2.977304563574816]]
['Bhutan', 29, [nan, 15.220439188896963, 0.034885235448586294, 0.315231652766427, 0.02289300966584239]]
['Bolivia', 56, [nan, 616.8748636529576, 2.0531305434959006, 0.9735354140851179, 2.2911851457152044]]
['Bosnia and Herzegovina', 50, [nan, 50.2448925244877, 255.69709591291152, 1.0963348745119788, 0.012490199922315096]]
['Botswana', 39, [nan, 1.6910989112739025, 0.030155015820407062, 0.012447849940057543, 0.04380002483329712]]
['Brazil', 83, [nan, 93.27061116270505, 112.41384989915552, 15.288688165222089, 0.2516536441269221]]
['Brunei Darussalam', 0, [nan]]
['Bulgaria', 66, [nan, 0.13949167318374472, 2.074278153152306, 16.866000292102758, 0.010083495994560427]]
['Burkina Faso', 44, [nan, 0.005480114887728389, 0.0428232125585634, 0.12594835150313796, 1.363006173362024]]
['Burundi', 49, [nan, 0.9447819121216154, 0.028516088699873033, 2.8388741438481904, 0.003797202471361445]]
['Cabo Verde', 43, [nan, 10.30275428380828, 0.03244077388808366, 0.06590200154051719, 0.0986849426811209]]
['Cambodia', 49, [nan, 0.01939675316602168, 50.146725655605536, 1.1432593484492746, 14.826048665093479]]
['Cameroon', 59, [nan, 0.5185612036828664, 0.7157758470083309, 20.467424286568665, 0.006822510458464413]]
['Canada', 118, [nan, 0.5140798044515154, 0.27429699813490754, 0.32394899338228594, 34.46405343206963]]
['Cayman Islands', 17, [nan, 1.2314367352392372, 0.08014607381370323, 0.16585526414994928, 0.007298959329163475]]
['Central African Republic', 0, [nan]]
['Chad', 0, [nan]]
['Channel Islands', 0, [nan]]
['Chile', 67, [nan, 0.025469555744639487, 23.9344867123796, 4.191946467179862, 0.18658885648821125]]
['China', 136, [nan, 2.5180148143804133, 0.587242242349768, 62.70648743585347, 5.596663559846415]]
['Colombia', 67, [nan, 23.339926708144773, 30.149485008798376, 118.2608803281599, 7.923744756886704]]
['Comoros', 31, [nan, 0.03092044158423078, 0.0015810340525444946, 0.15455072782664228, 0.21663850304355978]]
['Congo, Dem. Rep.', 70, [nan, 55.11097436840925, 12.927076854070235, 1.6821851110238066, 147.89432167689202]]
['Congo, Rep.', 0, [nan]]
['Costa Rica', 56, [nan, 0.4437834113398069, 2.367011322492874, 1.1242065774137326, 0.20753974994504845]]
["Cote d'Ivoire", 60, [nan, 3.3095015754121895, 0.0003264736795263502, 0.2730359119837978, 0.13426982854897368]]
['Croatia', 58, [nan, 4.444778738811572, 262.36426064349297, 252.71267471673642, 3.573786532690788]]
['Cuba', 0, [nan]]
['Curacao', 0, [nan]]
['Cyprus', 46, [nan, 0.19454632434067978, 80.21751276463445, 1.6906227060333272, 2.6813329698888397]]
['Czech Republic', 60, [nan, 7.56414357746857, 52.42052525425321, 149.5290244839472, 0.38865489099700384]]
['Denmark', 73, [nan, 0.5910444274300964, 1.226789693909528, 48.0285681785633, 7.176968047365457]]
['Djibouti', 29, [nan, 0.6731227900828911, 0.032597019760184115, 4.868937701237237, 0.013156171596623642]]
['Dominica', 48, [nan, 3.1320599946618537, 0.002577547416174295, 0.07955358792742945, 0.029547633217495144]]
['Dominican Republic', 63, [nan, 10.842093841550893, 4.096262271309658, 29.620815452372174, 1.644115549981684]]
['Ecuador', 56, [nan, 3.2589423365765056, 11.492588731385187, 3.56416277842586, 0.15579728378782057]]
['Egypt, Arab Rep.', 84, [nan, 0.0672323852386316, 1.8292964824244347, 409.93692975486016, 135.5035737179931]]
['El Salvador', 53, [nan, 0.2814630675986858, 51.111034621718915, 0.5948107708540081, 0.30872248804432595]]
['Equatorial Guinea', 0, [nan]]
['Eritrea', 0, [nan]]
['Estonia', 50, [nan, 0.1331654854465643, 10.43492657291591, 1.7351482057549006, 1.2817177974231815]]
['Eswatini', 35, [nan, 1.3169437850485322, 0.09671712211801342, 0.032318694803652945, 0.19765169425103876]]
['Ethiopia', 69, [nan, 0.030731785630703896, 0.010931077968785017, 8.217220741424223, 0.7469993844563525]]
['Faeroe Islands', 0, [nan]]
['Fiji', 43, [nan, 0.5590925637794699, 0.0018494686114373274, 170.00689111132044, 0.04521069929074665]]
['Finland', 61, [nan, 0.1988384654934581, 23.97263752991551, 5.038349422080311, 5.822326334660554]]
['France', 128, [nan, 7.916523155527783, 61.14530039462896, 1.8515625059890026, 120.11829517199523]]
['French Polynesia', 0, [nan]]
['Gabon', 40, [nan, 0.013014383976652652, 0.013397396864088165, 0.21346369229075038, 0.008363871873379024]]
['Gambia, The', 45, [nan, 0.5938847094921216, 3.402887254220875, 4.986927265093739, 0.03405348155637706]]
['Georgia', 52, [nan, 103.74653183451954, 2.37592959658247, 11.975644073351964, 133.5509863005214]]
['Germany', 122, [nan, 4.103914718007405, 1.9629762908734498, 0.4583873206709979, 50.32553501766768]]
['Ghana', 70, [nan, 0.1272967059235512, 39.67502987232777, 12.842339243402849, 0.22277273666051892]]
['Greece', 68, [nan, 19.25822497233019, 0.665913726567434, 0.6594170072838493, 71.49819033812099]]
['Greenland', 0, [nan]]
['Grenada', 43, [nan, 0.17858552538718692, 0.010058649291529182, 0.27079198908442503, 0.1434494860582182]]
['Guam', 0, [nan]]
['Guatemala', 56, [nan, 0.887173879649629, 7.151126414805893, 5.188173422949773, 0.35009493442222]]
['Guinea', 54, [nan, 8.374154421628747, 0.0006561334725496494, 1.0385696340301802, 0.43442564300165815]]
['Guinea-Bissau', 42, [nan, 0.047379847955512554, 0.24332814748552817, 1.0093423439802804, 1.6905050482367694]]
['Guyana', 52, [nan, 5.138168757382876, 0.2507041971831179, 0.5400986662369788, 0.019237515616026074]]
['Haiti', 62, [nan, 0.060584428948886035, 0.077096471639973, 3.8332992790781906, 0.368981198375038]]
['Honduras', 53, [nan, 0.03298235073659271, 0.3750873864321509, 2.6969753503851215, 1.118736929439433]]
['Hong Kong SAR, China', 37, [nan, 0.0018205849403058758, 47.68111958661088, 0.20527095201948747, 0.011833802111988192]]
['Hungary', 65, [nan, 3.739706387777373, 89.60920194212008, 408.3077603515358, 1.5240895862596349]]
['Iceland', 39, [nan, 0.037277137694082085, 2.6559960607033486, 0.9799298794550595, 1.1932625284486655]]
['India', 129, [nan, 0.3520630617585663, 0.4338405186872505, 1.7328735485796742, 3907.611281306092]]
['Indonesia', 88, [nan, 2.428220941062635, 0.03900488808378736, 195.945288764778, 3.42349831334106]]
['Iran, Islamic Rep.', 0, [nan]]
['Iraq', 73, [nan, 1.7248839041199877, 0.009114524742933594, 0.2584444185643955, 29.359382575540497]]
['Ireland', 70, [nan, 0.015339160438823668, 21.01704654500699, 0.3698175712047644, 0.014620137293253807]]
['Isle of Man', 0, [nan]]
['Israel', 71, [nan, 11.59863491526668, 258.8653345235127, 51.08738641138585, 7.842493359077115]]
['Italy', 107, [nan, 26.011948037265487, 2.2601464917326797, 1.5337821709413493, 0.2275733708917043]]
['Jamaica', 66, [nan, 11.249014726622196, 0.030360459094662305, 2.3981794545677517, 4.329528960534468]]
['Japan', 98, [nan, 0.12217096952130237, 28.9095094193566, 309.48761616223885, 19.00788634720831]]
['Jordan', 69, [nan, 11.13031772636729, 0.4055284932251458, 53.57591796274236, 6.899339112167841]]
['Kazakhstan', 60, [nan, 0.05489095001381291, 0.1853167780461075, 0.21342973167433613, 0.24135257410653616]]
['Kenya', 66, [nan, 0.011879370979037204, 198.45426139645704, 10.95402037347568, 0.13496720855453143]]
['Kiribati', 24, [nan, 3.0478577224136436, 0.2618806322559374, 0.008251089192314471, 0.007528328370947056]]
['Korea, Dem. Rep.', 0, [nan]]
['Korea, Rep.', 90, [nan, 1.0076389887727464, 28.118251374838128, 387.61384676365196, 8.706421577480276]]
['Kosovo', 22, [nan, 5.038429278179947, 119.47544001448279, 0.9649473772515449, 1.5147819034851646]]
['Kuwait', 55, [nan, 0.11685636127618136, 0.7438126750173318, 0.05603521760854431, 0.7077188159883406]]
['Kyrgyz Republic', 48, [nan, 2.5372256789786882, 4.401899479416901, 7.042695809582719, 15.851920961025998]]
['Lao PDR', 41, [nan, 0.048285505981349675, 2.3080959000615744, 0.027163033054278828, 12.601883117405846]]
['Latvia', 52, [nan, 0.41505789640642, 14.8185482603981, 6.608648371096577, 34.307025485369046]]
['Lebanon', 87, [nan, 7.03736833822451, 0.3508983392013182, 5.108681007184504, 5.100417353815112]]
['Lesotho', 28, [nan, 0.6266912944509145, 0.05611779318357797, 0.06464832650455776, 0.7176991559378184]]
['Liberia', 49, [nan, 6.875563505325247, 0.4128533520908553, 1.9553521401733978, 0.0016587376856989082]]
['Libya', 0, [nan]]
['Liechtenstein', 0, [nan]]
['Lithuania', 54, [nan, 0.479032366533295, 4.388420763612423, 2.071327861863764, 20.826965580495795]]
['Luxembourg', 43, [nan, 2.639681055225481, 8.249003297579629, 38.935295564575846, 407.30828615682344]]
['Macao SAR, China', 13, [nan, 0.400183666352407, 0.001955294786738145, 0.8068849819939411, 2.466017785034148]]
['Madagascar', 45, [nan, 0.01664314582623178, 1.298890931507105, 0.5645391749714698, 9.149309458629356]]
['Malawi', 44, [nan, 3.2207958261255527, 0.10859308901216591, 0.14815676386338, 0.006054790684279457]]
['Malaysia', 74, [nan, 0.6511155919577168, 0.001515985080227513, 144.2542954376455, 0.5224409048733134]]
['Maldives', 34, [nan, 0.9264956122220348, 0.016488162721125726, 0.008268234591704123, 0.012839966053490434]]
['Mali', 59, [nan, 0.13547845346893633, 0.21463928854151756, 1.7665314350589385, 2.3400761732196695]]
['Malta', 40, [nan, 0.005659963005844509, 114.31558599294117, 0.41917682262617806, 1.4724254673574355]]
['Marshall Islands', 14, [nan, 0.10645944328965386, 0.0027264733290215696, 0.0021540729552835536, 0.013649332717739807]]
['Mauritania', 45, [nan, 0.10571774880187637, 0.051981992372050215, 4.6251462490067015, 0.0011855084461340065]]
['Mauritius', 40, [nan, 46.66421186777916, 0.23205358992370267, 5.317557918049717, 0.3283824817979386]]
['Mexico', 71, [nan, 0.0164302187644837, 6.144971759019091, 35.79214092513657, 12.780545238186699]]
['Micronesia, Fed. Sts.', 0, [nan]]
['Moldova', 54, [nan, 0.8324345508045128, 2.4773050396809855, 8.868211461583215, 0.46376572958032103]]
['Monaco', 0, [nan]]
['Mongolia', 39, [nan, 38.356305993198895, 12.403133331725614, 0.7934587628780575, 5.158721099115565]]
['Montenegro', 38, [nan, 11.659141087264807, 12.320517299481844, 0.24482795450691522, 0.010733334718275641]]
['Morocco', 71, [nan, 1.2283067852411227, 0.6062030684507325, 8.749683052152111, 9.312636595304811]]
['Mozambique', 56, [nan, 0.13457057324005237, 0.009851722870509352, 1.4825650930183176, 0.14420331601454148]]
['Myanmar', 52, [nan, 0.005008296127330595, 29.510802426851317, 0.1081651986821367, 398.18910746980043]]
['Namibia', 43, [nan, 0.765484487806406, 0.001943443936108227, 1.9580559175000698, 0.3238174377035397]]
['Nepal', 64, [nan, 466.5764053747652, 3.0140107131780263, 9.386338459763751, 82.1803693939075]]
['Netherlands', 96, [nan, 0.6526598181945671, 0.062276700209405254, 0.9690254552583458, 13.598740257725732]]
['New Caledonia', 0, [nan]]
['New Zealand', 71, [nan, 0.016220423629230287, 0.00023981809129238328, 12.796908977684073, 0.011796058472385925]]
['Nicaragua', 54, [nan, 0.24193400154325706, 0.3354231061909664, 3.0058421942273963, 0.9704427436099088]]
['Niger', 49, [nan, 0.0022797211645953367, 0.17763294671756863, 0.13917287769897327, 8.134663438367333]]
['Nigeria', 94, [nan, 0.39939547717645396, 0.43443129522493573, 188.08797820216947, 109.39363853881076]]
['North Macedonia', 53, [nan, 0.41009109193120763, 1.2851182697106565, 45.32134546218967, 28.122260394697054]]
['Northern Mariana Islands', 0, [nan]]
['Norway', 62, [nan, 0.1988671559383854, 14.61848041020763, 3.146985520288134, 0.03837787219863578]]
['Oman', 43, [nan, 2.99430962068892, 0.11373621719375167, 0.10754278539447605, 0.035662173308323865]]
['Pakistan', 102, [369.3011409082328, nan, 0.022710098541072418, 550.6659914861618, 35.14508462140393]]
['Palau', 16, [nan, 0.025765569232081745, 0.0008660830061529641, 0.0008686096140627395, 0.018415758858609625]]
['Panama', 57, [nan, 0.6011289410344681, 1.1954670102302591, 0.33261515820712995, 0.20361483585503024]]
['Papua New Guinea', 35, [nan, 1.777748203452158, 0.0040605199478279995, 0.0015524307313811742, 3.1852818694049355e-05]]
['Paraguay', 51, [nan, 441.92730766350957, 0.4384142386214191, 0.16894858722061873, 0.4078731050531368]]
['Peru', 70, [nan, 424.16031608900295, 2.8246215934184296, 31.96860720259146, 5.062535195909173]]
['Philippines', 103, [nan, 4.9349707403682554, 2.0172465369841617, 0.28531929349930196, 5.857737666079258]]
['Poland', 75, [nan, 10.38849511075385, 74.86881954653286, 113.16231836306014, 0.028130233172905087]]
['Portugal', 80, [nan, 26.183999680718884, 12.01367490119337, 11.368950095460393, 0.4131687135331053]]
['Puerto Rico', 0, [nan]]
['Qatar', 43, [nan, 56.008122312470135, 1.6718842481334368, 7.829991228758263, 3.538821658549108]]
['Romania', 70, [nan, 2.190777602067845, 35.39656634604949, 294.01418992473117, 0.21766695586322657]]
['Russian Federation', 102, [nan, 0.6928491953671212, 1.678725056800337, 16.841972415280775, 26.795256785310855]]
['Rwanda', 55, [nan, 1.0411887418989558, 2.1394366376710723, 0.46299677310780635, 25.730609356161366]]
['Samoa', 33, [nan, 19.912611242558803, 64.3454266685056, 0.015520221257001046, 0.009753856301903143]]
['San Marino', 0, [nan]]
['Sao Tome and Principe', 32, [nan, 1.4096730848634569, 0.0068357726364150625, 0.000696836830401046, 0.05190978281882885]]
['Saudi Arabia', 68, [nan, 3.1302613891078126, 0.06501062074990265, 13.108070945346615, 0.765737765877121]]
['Senegal', 65, [nan, 2.1356986654041035, 1.856492300830287, 34.71406995029337, 0.021945317735044413]]
['Serbia', 50, [nan, 163.3492825129574, 742.8048884023029, 0.151047516856438, 2.732663466967111]]
['Seychelles', 36, [nan, 0.9882196504015475, 0.012122313017320745, 0.027070345735434164, 0.002881155987555481]]
['Sierra Leone', 50, [nan, 6.32445420197216, 0.31468117955220465, 3.900081423038167, 0.0014063408040436488]]
['Singapore', 0, [nan]]
['Sint Maarten (Dutch part)', 0, [nan]]
['Slovak Republic', 53, [nan, 34.81058211589252, 245.0462257281624, 0.125861854292839, 10.256262618328691]]
['Slovenia', 49, [nan, 3.7224798499470415, 33.45725116643792, 116.45231705057824, 1.408177493352527]]
['Solomon Islands', 24, [nan, 36.78365639920962, 0.24228550089860695, 0.027147270602446018, 0.007198373060689495]]
['Somalia', 65, [nan, 8.290328004603483, 0.0019370026286831801, 14.535219836754877, 10.90146398466525]]
['South Africa', 83, [nan, 5.340376736744133, 0.039893081523127885, 0.11478723197958758, 204.58406130455083]]
['South Sudan', 34, [nan, 33.64853937323647, 4.93475202920519, 21.06291251800823, 0.4369127812106429]]
['Spain', 88, [nan, 126.39263528492735, 0.0626382676218328, 563.7785749242889, 116.5836601414015]]
['Sri Lanka', 77, [nan, 0.0050456799924006816, 419.92218133577995, 2.9196543022269195, 0.10507281249929758]]
['St. Kitts and Nevis', 38, [nan, 0.3374146331232463, 0.03688703105600727, 0.0007423070939929108, 0.024384692163007038]]
['St. Lucia', 42, [nan, 0.5384418997835793, 0.0704634567382414, 0.018674145705307888, 0.06639805170576248]]
['St. Martin (French part)', 0, [nan]]
['St. Vincent and the Grenadines', 45, [nan, 1.1625978289552088, 0.16106975882681082, 0.0979173235915475, 0.0183579077169212]]
['Sudan', 70, [nan, 0.731464111487851, 0.004357632709925371, 14.239878491221559, 0.5897991738210642]]
['Suriname', 44, [nan, 0.021105762145785155, 0.002390579573451831, 0.7382315828320271, 0.09173118822065002]]
['Sweden', 75, [nan, 0.4913377602741667, 1.974985114827533, 111.36989232881113, 30.665256685346527]]
['Switzerland', 86, [nan, 0.3701177113468767, 3.4834608126764866, 61.091194002313884, 69.99579070471816]]
['Syrian Arab Republic', 0, [nan]]
['Tajikistan', 49, [15.575814029683867, nan, 1.1019579589360455, 3.9556655971287706, 0.9951095656149115]]
['Tanzania', 59, [nan, 0.0016610657466913964, 11.688567360322443, 0.6559095599984844, 1.8415311400723315]]
['Thailand', 81, [nan, 0.4437868569293174, 684.9507296425479, 55.16529862206673, 10.619724208504199]]
['Timor-Leste', 22, [nan, 56.01980526265993, 0.19639403451977455, 0.042721319088244836, 0.23693382709186378]]
['Togo', 50, [nan, 0.8467159159395489, 0.5234476095209717, 15.895978020715944, 115.50436818885574]]
['Tonga', 33, [nan, 2.4953634026925937, 43.17520580289032, 0.025521291391596205, 0.01140050029722483]]
['Trinidad and Tobago', 58, [nan, 0.4478614483321901, 0.019653494408194513, 1.2375715940682017, 0.06910961925317971]]
['Tunisia', 60, [nan, 0.0919751059151307, 1.8320735580158187, 10.809255403365857, 1.4074754481412413]]
['Turkey', 85, [nan, 0.352671444664467, 0.12299368663216723, 0.10342214835372562, 0.0021158504011522727]]
['Turkmenistan', 1, [nan, 1.15]]
['Turks and Caicos Islands', 0, [nan]]
['Tuvalu', 0, [nan]]
['Uganda', 58, [nan, 0.0016609203681251757, 11.113532498394521, 1.0353308449725878, 0.020592873803585907]]
['Ukraine', 76, [nan, 12.535778322325188, 6.503002953659741, 54.751295328650485, 52.99285793271208]]
['United Arab Emirates', 0, [nan]]
['United Kingdom', 138, [nan, 0.5787993887569002, 0.8400732816356543, 1.751201219691593, 0.7142473275580673]]
['United States', 153, [nan, 5.1353539870655, 2.4742020108468386, 5.901618042663587, 0.25849871755116227]]
['Uruguay', 59, [nan, 0.035290062795348694, 44.03838464667767, 3.8449965648624334, 0.10097025919120352]]
['Uzbekistan', 1, [nan, 9197.526464525383]]
['Vanuatu', 26, [nan, 0.13366438195033345, 91.66371046490285, 0.16284295968851317, 0.30478279955217913]]
['Venezuela, RB', 0, [nan]]
['Vietnam', 71, [nan, 0.8785659309820189, 0.02310556540566286, 1443.5656665964405, 19.568370420035386]]
['Virgin Islands (U.S.)', 0, [nan]]
['West Bank and Gaza', 59, [nan, 25.829159509695252, 3.309229519445729, 0.6703794831176282, 6.333127276190841]]
['Yemen, Rep.', 0, [nan]]
['Zambia', 56, [nan, 0.2654129013904418, 0.0011678912523574306, 12.401076052888659, 0.23158303644324485]]
['Zimbabwe', 58, [nan, 0.003246397797964181, 105.03703179714542, 0.9057889458537597, 0.02560127127433617]]
['WORLD', 214, [384.87695493791665, 51.682369337708366, 79.09641083814145, 38.22409614982712, 230.66873853457403]]

In [45]:
# Replacing missing values with zero
df5.fillna(0, inplace=True)

# Rename 'Remittance-sending country' column to 'Country Name'
df5.rename(columns={'Remittance-sending country': 'Sending Country'}, inplace=True)

df5.head()

,Sending Country,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Aruba,Australia,Austria,Azerbaijan,"Bahamas, The",Bahrain,Bangladesh,Barbados,Belarus,Belgium,Belize,Benin,Bermuda,Bhutan,Bolivia,Bosnia and Herzegovina,Botswana,Brazil,Brunei Darussalam,Bulgaria,Burkina Faso,Burundi,Cabo Verde,Cambodia,Cameroon,Canada,Cayman Islands,Central African Republic,Chad,Channel Islands,Chile,China,Colombia,Comoros,"Congo, Dem. Rep.","Congo, Rep.",Costa Rica,Cote d'Ivoire,Croatia,Cuba,Curacao,Cyprus,Czech Republic,Denmark,Djibouti,Dominica,Dominican Republic,Ecuador,"Egypt, Arab Rep.",El Salvador,Equatorial Guinea,Eritrea,Estonia,Eswatini,Ethiopia,Faeroe Islands,Fiji,Finland,France,French Polynesia,Gabon,"Gambia, The",Georgia,Germany,Ghana,Greece,Greenland,Grenada,Guam,Guatemala,Guinea,Guinea-Bissau,Guyana,Haiti,Honduras,"Hong Kong SAR, China",Hungary,Iceland,India,Indonesia,"Iran, Islamic Rep.",Iraq,Ireland,Isle of Man,Israel,Italy,Jamaica,Japan,Jordan,Kazakhstan,Kenya,Kiribati,"Korea, Dem. Rep.","Korea, Rep.",Kosovo,Kuwait,Kyrgyz Republic,Lao PDR,Latvia,Lebanon,Lesotho,Liberia,Libya,Liechtenstein,Lithuania,Luxembourg,"Macao SAR, China",Madagascar,Malawi,Malaysia,Maldives,Mali,Malta,Marshall Islands,Mauritania,Mauritius,Mexico,"Micronesia, Fed. Sts.",Moldova,Monaco,Mongolia,Montenegro,Morocco,Mozambique,Myanmar,Namibia,Nepal,Netherlands,New Caledonia,New Zealand,Nicaragua,Niger,Nigeria,North Macedonia,Northern Mariana Islands,Norway,Oman,Pakistan,Palau,Panama,Papua New Guinea,Paraguay,Peru,Philippines,Poland,Portugal,Puerto Rico,Qatar,Romania,Russian Federation,Rwanda,Samoa,San Marino,Sao Tome and Principe,Saudi Arabia,Senegal,Serbia,Seychelles,Sierra Leone,Singapore,Sint Maarten (Dutch part),Slovak Republic,Slovenia,Solomon Islands,Somalia,South Africa,South Sudan,Spain,Sri Lanka,St. Kitts and Nevis,St. Lucia,St. Martin (French part),St. Vincent and the Grenadines,Sudan,Suriname,Sweden,Switzerland,Syrian Arab Republic,Tajikistan,Tanzania,Thailand,Timor-Leste,Togo,Tonga,Trinidad and Tobago,Tunisia,Turkey,Turkmenistan,Turks and Caicos Islands,Tuvalu,Uganda,Ukraine,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Vanuatu,"Venezuela, RB",Vietnam,Virgin Islands (U.S.),West Bank and Gaza,"Yemen, Rep.",Zambia,Zimbabwe,WORLD
0,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0,0.0,0.00000,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.000000,0.0,0.000000,0.0,0.0,0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,369.301141,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,15.575814,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,384.876955
1,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0,0.0,0.00000,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.51408,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,19.258225,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.000000,0.0,0.000000,0.0,0.0,0,26.011948,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0,0.410091,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.352671,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,5.135354,0.00000,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,51.682369
2,Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0,0.0,0.00000,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,7.916523,0.0,0.0,0.0,0.0,4.103915,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2.428221,0.0,1.724884,0.0,0.0,0,2.260146,0.0,0.0,11.130318,0.0,0.0,0.0,0.0,0.000000,0.0,0.116856,0.0,0.0,0.0,7.037368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.651116,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000,0.0,0.0,0.0,0.692849,0.0,0.000000,0.0,0.0,3.130261,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.290328,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.731464,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.578799,2.474202,0.00000,0.0,0.0,0.0,0.000000,0.0,25.82916,0.0,0.0,0.0,79.096411
3,American Samoa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0,0.0,0.00000,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.00000,2.518015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.559093,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.000000,0.0,0.000000,0.0,0.0,0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,1.007639,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.01622,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,4.934971,0.0,0.000,0.0,0.0,0.0,0.000000,0.0,19.912611,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,2.495363,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,5.901618,0.00000,0.0,0.0,0.0,0.878566,0.0,0.00000,0.0,0.0,0.0,38.224096
4,Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.58971,0,0.0,0.10475,0.0,0,0.0,0.0,0.0,0.0,0.0,6.24554,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.02547,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.591044,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,61.145300,0.0,0.0,0.0,0.0,1.962976,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.000000,0.0,0.000000,0.0,0.0,0,1.533782,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.228307,0.0,0.0,0.0,0.0,0.65266,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,2.017247,0.0,26.184,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,126.392635,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.491338,0.370118,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.840073,0.258499,0.03529,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,230.668739

In [46]:
# Save to Excel

df5.to_excel('bilateral_remittance_matrix_2021_CLEANED.xlsx', index=False)